### ISSUE TITLE
nfd-master: skip nodes that don't have any NodeFeature objects

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1894]
**What would you like to be added**:

No not try to process NodeFeatureRule object(s) for nodes that don't have any NodeFeature object(s). Prevents flood of errors from failing rules (because the nodes don't have any features). We could log (info) that the node is skipped.

Ref: https://github.com/kubernetes-sigs/node-feature-discovery/discussions/1892

**Why is this needed**:

Drop misleading errors, increase user comfort

**Comment by marquiz** [comment]
/milestone-0.17
/help

**Comment by Kavinraja-G** [comment]
@marquiz I would like to work on this. Thanks!
/assign

**Comment by Kavinraja-G** [comment]
@marquiz -- Apologies for the delay. I'm currently reviewing this, and since it's a new codebase, I would appreciate your suggestions.

To clarify, are we just looking to skip the `processNodeFeatureRule` [here](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/pkg/nfd-master/nfd-master.go#L985) if the `features` object is `nil`?

**Comment by marquiz** [comment]
After sleeping over this for a few weeks I think a better fix (for now, at least) would be to just not return an error in case a feature is not found. We could log this as info (say with `V(2)`) and then carry on. This wouldn't e.g. break the corner case of empty rules that always match.

**Comment by googs1025** [comment]
Is this still active? If not, I'd like to try this 🤔

**Comment by Kavinraja-G** [comment]
Apologies, I’ll get this going this week.
