### ISSUE TITLE
Add e2e tests for node-feature-discovery

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-sigs/node-feature-discovery#33]
Tests could be similar to what's been implemented for node-problem-detector: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node_problem_detector.go

**Comment by balajismaniam** [comment]
@okartau @marquiz Can you please take a look at this? An implementation of the test can be found in https://github.com/balajismaniam/kubernetes/tree/e2e-tests-for-nfd. Note that while the implementation example is a part of the Kubernetes repo, it is not expected to land there anymore. The e2e test should be a part of the NFD repo.

**Comment by okartau** [comment]
I will start looking, but need some time to get familiar with e2e overall. Seems e2e does not run using go 1.8 so I need to prepare something else than my current CentOS-87 based cluster. BTW, is/was the original e2e-tests-for-nfd implementation functional or just example?

**Comment by balajismaniam** [comment]
@okartau Thanks. Yes the implementation was functional. I haven't tried to run with current k8s. However, it should work with very minimal changes.

**Comment by okartau** [comment]
As first step I tried in current location (k8s/test/e2e) to make smaller steps. APIs have changed but with few changes I got a code that builds,  Running however does not work. The exact output from pod remains hidden (I still have to learn how to make that visible), but signs indicate that RBAC may block
operation here as well, similar to what I discovered in validation with recent k8s:
- pod run turns to "failed" with regular code, and e2e test fails.
- pod run gets marked "success" when "--no-publish" is added to arguments , and e2e test fails as well
although pod ran ok, it did not attempt to give labels.

Although there are RBAC role rights added in the cluster I use so that regular NFD runs,
it seems e2e test system creates own layer of things and needs separate RBAC setup?

For code relocation: relocating the testing code into NFD repo should be possible independent  from getting-to-run work. Where will we put the code in the NFD repo?

**Comment by okartau** [comment]
run preserving failed pod and logs (--delete-namespace-on-failure=false), show pod output:
2018/05/02 10:40:42 node.alpha.kubernetes-incubator.io/node-feature-discovery.version = v0.1.0-52-g01e2110-dirty
2018/05/02 10:40:42 node.alpha.kubernetes-incubator.io/nfd-fake-fakefeature1 = true
2018/05/02 10:40:42 node.alpha.kubernetes-incubator.io/nfd-fake-fakefeature2 = true
2018/05/02 10:40:42 node.alpha.kubernetes-incubator.io/nfd-fake-fakefeature3 = true
2018/05/02 10:40:42 can't get node: resource name may not be empty
2018/05/02 10:40:42 failed to get node: resource name may not be empty
2018/05/02 10:40:42 failed to advertise labels: resource name may not be empty
2018/05/02 10:40:42 error occurred while updating node with feature labels: resource name may not be empty
2018/05/02 10:40:42 NODE_NAME: 

so this seems different than RBAC-related issue, right?

**Comment by okartau** [comment]
Failure above turned out to be related to recent NFD code change where we streamlined getting of node name, leaving out POD_ names steps. Code on e2e test side was still using older approach. With that one unified to latest, we finally hit the RBAC fail that I anticipated:
2018/05/02 11:49:50 NODE_NAME: k8-175-14
2018/05/02 11:49:50 can't get node: nodes "k8-175-14" is forbidden: User "system:serviceaccount:e2e-tests-node-feature-discovery-tfc4f:default" cannot get nodes at the cluster scope

Means, I start looking how to add RBAC related rights in the e2e code.

**Comment by balajismaniam** [comment]
@okartau Thanks for looking into this. It might not be a good idea to vendor test artifacts in NFD. I was thinking more in terms of running our own e2e tests and pointing it to a cluster. 

An example of this can be seen in https://github.com/kubeflow/experimental-kvc. We have e2e tests in https://github.com/kubeflow/experimental-kvc/blob/master/test/e2e/kvc_test.go and these tests are run against an already existing cluster using https://github.com/kubeflow/experimental-kvc/blob/master/.circleci/config.yml#L60. In KVC's case we use CircleCI. However, you can use Travis to run the e2e tests as well.

**Comment by balajismaniam** [comment]
@okartau @marquiz Is there any update on this? This will help us avoid situations like #134  and https://github.com/kubernetes-incubator/node-feature-discovery/pull/134#discussion_r197211761. 

CC @poussa @josepalafox

**Comment by marquiz** [comment]
@balajismaniam: I now start looking into this

**Comment by okartau** [comment]
I have a proto-level trial implementation, in stand-alone  style so that it does not need k8s e2e framework. I planned to push it as PR but I felt it needs cleaning up, which I haven't got onto yet. But please wait for it, to avoid double effort

**Comment by okartau** [comment]
I pushed my current trial into okartau:add-e2e-trial, hopefully better starting point than zero

**Comment by marquiz** [comment]
#158 contains an RFC implementation of simple e2e test. It runs nfd image on a k8s cluster and checks that the labels from the *fake* feature source are correctly applied. The implementation uses previous work from @balajismaniam and @okartau.

We don't yet have a (public) cluster to run against, so the travis part is completely missing.

**Comment by marquiz** [comment]
#181 updated: it was adapted to the recent master/worker split, and, some issues with the test itself were fixed.

**Comment by Ethyling** [comment]
@marquiz We can close this issue as https://github.com/kubernetes-sigs/node-feature-discovery/pull/186 is merged and working fine! :smiley:

**Comment by marquiz** [comment]
Yes, thanks a lot @Ethyling !
