### ISSUE TITLE
Branchprotector errors, gh-pages job is required but protection = false

### ISSUE THREAD

**Issue by michelle192837** [kubernetes-sigs/node-feature-discovery#425]
**What happened**:
Prow is getting an error periodically (1/hour) in the logs when running branch protector:

```
jsonPayload: {
  component: "branchprotector"   
  error: "update kubernetes-sigs: update node-feature-discovery: update gh-pages from protected=false: get policy: required prow jobs require branch protection"   
  file: "prow/cmd/branchprotector/protect.go:143"   
  func: "main.main"   
  level: "error"   
  msg: "0"   
 }
```
I suspect this is either due to a configuration change (though I don't think there's a recent enough relevant change), or because this job was made required in GitHub recently?

**What you expected to happen**:
Running without error.

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:
From logs, it looks like this started popping up on January 14th. (First instance seems to be 1-14 at 9 AM PST).

**Comment by marquiz** [comment]
I have no idea why that started happening. NFD-related prow configs haven't been changed in a while.

Branch protection for the gh-pages branch was removed in https://github.com/kubernetes/test-infra/pull/19770. Could it be because the presubmit jobs (https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/node-feature-discovery/node-feature-discovery-presubmits.yaml) have no `branches` filter?

**Comment by marquiz** [comment]
Submitted https://github.com/kubernetes/test-infra/pull/20532 in an attempt to fix this

**Comment by michelle192837** [comment]
Thanks! I'm not seeing any error logs for this now, so looks like it's fixed!
