### ISSUE TITLE
Two different instances NFD should not override labels

### ISSUE THREAD

**Issue by e0ne** [kubernetes-sigs/node-feature-discovery#427]
**What would you like to be added**: NDF should be able to work in a concurrency with several NFD instances and don't override labels

**Why is this needed**: In a complex deployments we can have several instances of NFD deployed and configured by different operators or k8s cluster is used for multiple purposes

**Comment by e0ne** [comment]
Possible solutions how to implement this feature:

1. Add `--label-ignorelist` which will work in pretty same way as `--label-whitelist` but just will read labels from node and keep them in the list.
2. Add new `labels` source where we can specify which labels we should leave 'as is'
3. nfd-worker should store labels list somewhere in k8s(e.g. shared ConfigMap between several instances) and nfd-master will read them before applying to the node.

**Comment by marquiz** [comment]
This might be a bit more involved than it seems at first. I think we'd want to maintain the relatively simple stateless operation of NFD. NFD-Worker is a fully stateless daemon with no connection to the K8s control plane which seems to rule out # 3 of the possible solutions above. # 2 I don't fully understand but looks like similarly confrontational. The problem with # 1 is that we store the some metadata in node annotations. E.g. the names of nfd-managed labels in `nfd.node.kubernetes.io/feature-labels`. One way to extend this could be e.g. something like `--instance` flag in nfd-master which would change the annotation namespace/prefix to `<instance>.nfd.node.kubernetes.io`. Do you really need to filter out the labels on the nfd-master side? I think it would be more versatile and maintainable to configure it on the worker side of each parallel deployment. I think the command line flags are awkward to use and e.g. `--label-whitelist` is a legacy flag that I'm thinking we might want to deprecate.

What is the main restriction why you couldn't use just one deployment of NFD? Related to configuration handling or something different? I'm just thinking that what would be the other, possibly simpler, ways to implement your use case.

**Comment by e0ne** [comment]
@marquizWe can't filter labels on the worker side because each instance has only a list of own labels.

I agree it's better do not use CLI args in k8s but it's out of the scope of this patch.

We've got several NFD instances controlled by different operators. We don't want to mix them together because they're responsible for different areas

**Comment by moshe010** [comment]
In our case with have Network Operator which provide nfd to label network stuff (nfd Network config)  and GPU operator which provide nfd lablel for GPU stuff (nfd GPU config). both can work together or standalone. We don't wont to force dependency. Some provide their own nfd hook as well so the other is not aware of it.

**Comment by marquiz** [comment]
> @marquizWe can't filter labels on the worker side because each instance has only a list of own labels.

Hmm, I'm not sure I understand 🤔  Are you talking about multiple instances (deployments) of nfd-master of one nfd-master serving multiple deployments of nfd-worker.

The worker side should be able to enable only labels that it's responsible for. The `--instance` solution I outlined above should provide separation of "label spaces". And OTOH, how big of a problem is it if two instances manage the same label – ideally the value should be the same independent of the instance it is originating from.

**Comment by marquiz** [comment]
> In our case with have Network Operator which provide nfd to label network stuff (nfd Network config) and GPU operator which provide nfd lablel for GPU stuff (nfd GPU config). both can work together or standalone. We don't wont to force dependency. Some provide their own nfd hook as well so the operator is not aware of it.

I see. I think the `--instance` could be a simple solution for parallel deployments. Longer term, we should think ways to serve multiple independent users/configurations of NFD from a single deployment. E.g. config CRDs or something...

**Comment by e0ne** [comment]
@marquiz Do you propose to change label names with instance prefix? If yes, it could affect current users

**Comment by marquiz** [comment]
> @marquiz Do you propose to change label names with instance prefix? If yes, it could affect current users

Nope, just the annotation

**Comment by marquiz** [comment]
The `--instance` flag was such a simple idea that I decided to see how it would look like. You can take a look (and test) at #431. It virtually untested so beware... I'll try it out tomorrow, myself.

**Comment by marquiz** [comment]
Routing back the discussion in #431 here.

https://github.com/kubernetes-sigs/node-feature-discovery/pull/431#issuecomment-773272609:
> E..g.:
> instance1: --label-whitelist=pci-0300_102b.present"
> instance2: --label-whitelist=pci-8086.sriov.capable"
> 
> As a result, I would like to have a list of labels which contains both pci-0300_102b and pci-8086.sriov features discovered on the one node

Could you elaborate a bit? You have two NFD instances publishing different labels and then you'd like to do...?

**Comment by e0ne** [comment]
In other words, master should merge labels provided by different workers. So if worker 1 publishes label A and worker 2 publishes label B the result should be A,B

**Comment by zvonkok** [comment]
The GPU operator will likely use the default config but the network operator would have some additional rules to detect sriov or rdma capable. The network operator will likely add more features that need to be published to a node.

**Comment by marquiz** [comment]
> In other words, master should merge labels provided by different workers. So if worker 1 publishes label A and worker 2 publishes label B the result should be A,B

Hmm, this is something totally different from *different instances NFD should not override labels*. It should be carefully evaluated what would be the best way to implement/achieve these kind of "meta labels". I'm not sure if nfd-master would be the correct place to do this. Maybe it should be one worker which should be able to consume "rules" from multiple sources instead of having 10x NFD parallel deployments.

**Comment by marquiz** [comment]
> The GPU operator will likely use the default config but the network operator would have some additional rules to detect sriov or rdma capable. The network operator will likely add more features that need to be published to a node.

This I understand and it should be possible to achieve with just two NFD deployments running in parallel. Network operator would only enable e.g. the `custom` source with its specific rule(s) in place

**Comment by moshe010** [comment]
In our case we use the --label-whitelist to put the relevant labels. The problem is in the [1] each NFD master will get the oldLabels and remove them (even labels which are not match to the whitelist). Maybe we should filter the oldLabels that match the whitelist and remove just them  (instead of adding the --ignore-flag). IMHO it make sense that --label-whitelist will defined the scope of labels that NFD allow to add/delete. (currently implementation just work for add) 

WDYT? 

https://github.com/kubernetes-sigs/node-feature-discovery/blob/a0f59ef22f9de0d1215240afde4cf74720a6cb2f/pkg/nfd-master/nfd-master.go#L438-L445

**Comment by marquiz** [comment]
> IMHO it make sense that --label-whitelist will defined the scope of labels that NFD allow to add/delete. (currently implementation just work for add)

That would be possible, but, I think it's better how it is now. With the current setup NFD is able to remove outdated labels in casea you change the configuration (e.g. alter `--label-whitelist`). Also, this would be inherently racy as multiple deployments would compete on the same annotations -> bad

Have you looked at #431 which will resolve this issue?

**Comment by moshe010** [comment]
you PR solves half of the problem. Only the annotation part [1] but it is not solve the nfd label overwrite [2]. Maybe we should update your PR that in case of --instance and --whitelist we should remove only labels in the --whitelist.


[1] 
Annotations:                    
                    nfd.node.kubernetes.io/extended-resources: 
                    nfd.node.kubernetes.io/feature-labels:
                      cpu-cpuid.AESNI,cpu-cpuid.AVX,cpu-cpuid.IBPB,cpu-cpuid.STIBP,cpu-cpuid.VMX,cpu-hardware_multithreading,cpu-pstate.turbo,custom-rdma.availa...
                    nfd.node.kubernetes.io/master.version: v0.6.0-204-gf0513ee
                    nfd.node.kubernetes.io/worker.version: v0.6.0

[2] - 
Labels:          
                    feature.node.kubernetes.io/cpu-cpuid.AESNI=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX=true
                    feature.node.kubernetes.io/cpu-cpuid.IBPB=true
                    feature.node.kubernetes.io/cpu-cpuid.STIBP=true
                    feature.node.kubernetes.io/cpu-cpuid.VMX=true
                    feature.node.kubernetes.io/cpu-hardware_multithreading=true
                    feature.node.kubernetes.io/cpu-pstate.turbo=true
                    feature.node.kubernetes.io/custom-rdma.available=true
                    feature.node.kubernetes.io/custom-rdma.capable=true

**Comment by marquiz** [comment]
> it is not solve the nfd label overwrite [2]. Maybe we should update your PR that in case of --instance and --whitelist we should remove only labels in the --whitelist.

I still think this is a bad idea.

Overwriting labels is a configuration problem. I re-iterate that I think this configuration problem should be handled on the worker side, rather than on the master side. From the operator/deployment POW it shouldn't really matter whether to configure the master or the worker. When having multiple deployments of NFD running in parallel, there is really no reliable way to enforce label separation and prevent overlap (that is, to prevent different deployments modifying the same labels). An incorrect deployment/configuration of one NFD instance will ruin everything as all the nfd-master instances have full authorization to update any aspect of the K8s node object.

In your example above ([2]), I fail to see what the problem is if two deployments would create the same labels with the same values. Again, if different deployments tried to create the same labels with different values it would clearly be a configuration error. This shouldn't really happen with the "built-in" feature sources. If it's about custom labels (from the `custom` source or hooks in `source.d/` or files from `features.d/`), different deployments should use a different label name, e.g. by using a dedicated label namespace like `vendor-a/feature-x` and `vendor-b/feature-x`.

**Comment by moshe010** [comment]
@marquiz thanks for the explain I went over the code and I think you are right that we only need the --instance. The code remove the existing label which are stored in the annotation [1].  We will check it again and update. 

[1] - https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/pkg/nfd-master/nfd-master.go#L395

**Comment by moshe010** [comment]
@marquiz thanks, worked as expected.

**Comment by marquiz** [comment]
@e0ne cat we close this issue?

**Comment by e0ne** [comment]
@marquiz yet, let's close it
