### ISSUE TITLE
node-feature-discovery image has incorrect version

### ISSUE THREAD

**Issue by e0ne** [kubernetes-sigs/node-feature-discovery#448]
**What happened**:
Images published to gcr.io/k8s-staging-nfd/node-feature-discovery have incorrect version. E.g.: v0.6.0-235-gaccb986. T

**What you expected to happen**:
he latest tag is v0.7.0, to it should be something like v0.7.0-235-gaccb986

**Anything else we need to know?**:
It looks like `git describe --tags --dirty --always` command (https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/Makefile#L27) ignores not annotated tags.  I'm not sure what is a correct way to fix if for v0.7.0 but we should not forget to create an annotated flag for the each new release like v.0.8.0 #437

**Comment by marquiz** [comment]
This is a bit unfortunate and caused by the fact that we started to create releases (tags) out of release branches. Thus, we will not be able to get version like `v0.7.0-235-gaccb986`, and, we shouldn't, as the master is not an ancestor of v0.7.0.

I agree that this is confusing and it would be nice to address it somehow. There are at least few options I can think of:
1. Drop the tag name for versions that are not a tagged revision, exactly. Just have use a dummy version, running commit count and the commit hash, i.e. something like `v0.0.0-1234-g12345abcd`
2. Create some `pre` or `alpha` or `devel` tag when branching out a release branch, i.e. we would have something like `v0.7.0-devel-123-g1234abcd`

**Comment by e0ne** [comment]
I don't have strong preferences on it. Both options will resolve this issue. Option 1 looks a bit better because it doesn't afffect current development workflow

**Comment by marquiz** [comment]
I now solved this by pushing an unannotated tag `v0.9.0-devel` into the repo. Current tip of master branch gives version like:
```
nfd-worker v0.9.0-devel-14-gc06e92fe
```
