### ISSUE TITLE
Improvements for cert-manager support

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#478]
**What would you like to be added**:

From #379 :

- [ ] use cert-manager-csi (looks to be in early stages still) to get per node nfd-worker certs
- [ ] support `-verify-node-name`
- [x] use kustomize for enabling cert-manager for deployment specs

**Why is this needed**:

Fully integrate all NFD TLS options with cert-manager. Increased security. Better user experience

**Comment by zvonkok** [comment]
+1 for that @marquiz find the way of using a mutating webhook for automatic injection of certs clumsy, that's how it is done now in the operator sdk. Like the CSI approach.

**Comment by marquiz** [comment]
ping @dbaker-rh are you familiar with cert-manager-csi, have you been following it?

**Comment by dbaker-rh** [comment]
(note - minor typo in the issue description; should be NODE name, not MODE name)

No, I've not spent any time looking at cert-manager-csi though at first glance it looks like it might be a good fit and relatively easy to plumb in.

However, I'm not sure what the cost/benefit of additional infrastructure versus the (imho relatively small) advantage of being able to enable the --verify-node-name flag.  If certificate generation gets automated to this extent then I question the benefit of verifying the node name since the creation of a valid/verifyable certificate has such a low barrier to entry.

Put another way, what does "--verify-node-name" protect from in this situation?  Any threat actor with permissions "inside" this namespace can already generate their own certs.  A threat actor outside the namespace might attempt to steal and re-use a cert but this can (perhaps) be better addressed with shrinking the validity period.

Regarding the issue description:
- Why is this more secure?  (specifically, what does it protect against?)
- How is this a better user experience?  (specifically, what does the user gain?)

Conceptually, I agree that enabling security flags is wise, but I don't see a good story here.  Running NFD without tls is, imho, insanity.  However, running NFD without --verify-node-name gets us to ~99% of the benefit and only ~1% of the complexity.


$0.02 ... perhaps I'm missing something obvious?  Will be happy to think on this some more, and see if I change my mind on any of the observations above.

(Also, did I accidentally obsolete #379? From a quick review of it, the content there looks to have been duplicated by my recent PRs to support cert-manager in kustomize and helm.  If no objections perhaps you (@marquiz) can review and close it?)

**Comment by marquiz** [comment]
Thanks @dbaker-rh, meritious pondering.

TBH, I haven't really given much thought to this myself, but just happened to pick this up now while browsing through open issues.

It might very well be the case that it's not worth the trouble. Especially because we're managing nfd-master and nfd-worker (and topology-updater) together, they're running in the same namespace and cert-manager handles cert rotation etc. As you pointed out, in the current setup the benefits are probably negligible, and thus, wouldn't justify the added work/complexity.

Any thoughts on this @mythi @zvonkok? I would be ok closing this issue for now and get back to it if seen important in the future.

> (Also, did I accidentally obsolete #379?

Nope, that was an old one on the deployment templates which were replaced by kustomize.

> (note - minor typo in the issue description; should be NODE name, not MODE name)

Fixed 😊

**Comment by mythi** [comment]
> Any thoughts on this @mythi @zvonkok? I would be ok closing this issue for now and get back to it if seen important in the future.

@marquiz I'm OK with this. The only justification to keep this open would be that if someone was looking for this particular use-case it would be easier to find that it's a gap still.

**Comment by marquiz** [comment]
Thanks @dbaker-rh and @mythi for the feedback! Let's close this for now as nobody is requesting this or actively working on this. Let's be happy with the kustomize support that was implemented 😉 

/close
